### ISSUE TITLE
Gerar token do cartão de crédito

### ISSUE THREAD

**Issue by jlccaires** [pagseguro/pagseguro-java-sdk#1]
Não encontrei nenhum exemplo de como gerar um token para pagamento com cartão de crédito.
Como esse procedimento deve ser feito via API java?

**Comment by gabriellucius** [comment]
Olá @jlccaires!

Esse tipo de ação (obter o token do cartão de crédito, por exemplo) é feita através de funções JavaScript que devem ser importadas e executadas no browser.

A [documentação completa pode ser acessada aqui](https://dev.pagseguro.uol.com.br/documentacao/pagamentos/pagamento-transparente), nela há um passo a passo de todo o fluxo a ser executado, tanto em Produção quanto em Sandbox, inclusive [como obter o token do cartão de crédito](https://dev.pagseguro.uol.com.br/documentacao/pagamentos/pagamento-transparente#obter-token-cartao).

**Comment by kozfelipe** [comment]
esses links de documentação não existem mais

**Comment by altencir** [comment]
Qual seria o endpoint para obter o TOKEN do Cartão de Creditos?
Seria esse: https://df.uol.com.br/v2/cards/ ?
A documentação só dá o exemplo.
