### ISSUE TITLE
Endereço do repositório de dependências não é público.

### ISSUE THREAD

**Issue by iranmarcius** [pagseguro/pagseguro-java-sdk#20]
Clonei o projeto para utilizar a API de pagamentos para integração. Instalei o Gradle e executei o comando "grable build" na pasta source como informado na documentação.

Ocorreram erros de compilação devido à falta de dependências o projeto. Analisando o arquivo de configurações verifiquei que o endereço do repositório não é acessível publicamente.

Acrescentei um repositório público no build.gradle build foi feito sem problemas.

	maven {
		url 'http://repo1.maven.org/maven2/'
	}

Uma vez que é um projeto público, que pode ser baixado e utilizado por outros desenvolvedores, acredito que o endereço do repositório também deve ser público para evitar contratempos.

**Comment by gabriellucius** [comment]
Olá @iranmarcius 

Já estamos providenciando a publicação no repositório global do Maven para resolver esse problema.
Esse problema já foi relatado na issue https://github.com/pagseguro/pagseguro-java-sdk/issues/3
Obrigado pela colaboração!

**Comment by salviof** [comment]
Tem um pull request com esta correção que funcionou pra mim, o pull request #17 @iranmarcius

**Comment by iranmarcius** [comment]
Obrigado @salviof . Já havia resolvido por aqui mesmo mudando o endereço do repositório no arquivo do Gradle.
