### ISSUE TITLE
Problemas para compilar com o Gradle | repositório inválido.

### ISSUE THREAD

**Issue by JonasXPX** [pagseguro/pagseguro-java-sdk#3]
Olá, o endereço fornecido no repositório, abaixo, não está funcionado.

> http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/

Apenas este está funcionado corretamente #8. 

> https://repository-master.mulesoft.org/nexus/content/groups/public/

**Comment by gabriellucius** [comment]
Olá @JonasXPX 

Já estamos providenciando a publicação no repositório global do Maven.

Obrigado pela colaboração!

**Comment by CatatauNoob** [comment]
Olá o repositório abaixo não contém br.com.uol.pagseguro:pagseguro-api:jar:1.0-SNAPSHOT

https://repository-master.mulesoft.org/nexus/content/groups/public/

Fico no aguardo da correção.

**Comment by cesarcaos** [comment]
Dois testes falharam durante a instalação no Windows via Gradle: 
RequestMapTest. shouldConvertToHttpRequestBody
RequestMapTest. shouldConvertToUrlEncode

O que devo fazer?

Desde já, agradeço.

**Comment by cesarcaos** [comment]
Só para complementar...

No caso do teste RequestMapTest. shouldConvertToHttpRequestBody, tem a seguinte mensagem no report:
java.lang.AssertionError: expected:<HttpRequestBody{content='key1=value1&key2=value2', charset='UTF-8', contentType='application/x-www-form-urlencoded; charset=UTF-8'}> but was:<HttpRequestBody{content='key2=value2&key1=value1', charset='UTF-8', contentType='application/x-www-form-urlencoded; charset=UTF-8'}>

No caso do teste RequestMapTest. shouldConvertToUrlEncode, apareceu a seguinte mensagem:
org.junit.ComparisonFailure: expected:<key[1=value1&key2=value2]> but was:<key[2=value2&key1=value1]>

**Comment by fincatto** [comment]
Caros, bom dia.
Providenciei um PR com a correção: https://github.com/pagseguro/pagseguro-java-sdk/pull/17
Uma versão já corrigida encontra-se em: https://github.com/wmixlabs/pagseguro-java-sdk
Att

**Comment by filipe-damasceno** [comment]
Estou tendo problemas ao dar o build 

br.com.uol.pagseguro.api.transaction.register.DirectPaymentRegisterResourceTest > shouldBankSlipRegister FAILED

**Comment by madnilo** [comment]
@filipe-damasceno 

Tive o mesmo problema, apaguei os testes e buildou.

**Comment by ramiresnas** [comment]
Boa noite, esse sdk já está funcionando? vou iniciar um projeto e estou vendo que tem alguns problemas.

**Comment by filipe-damasceno** [comment]
@ramiresnas Cara está funcionando sim, no meu caso o problema era referente ao repositório alterei o endereço e deu certo. Porem acabei optando por não utilizar o SDK, fiz através de chamadas ao web service do PagSeguro. No meu caso só preciso fazer checkout e ficar acompanhando o status das transações, quando a transação tem o pagamento confirmado realizo algumas ações.

**Comment by gabriellucius** [comment]
@ramiresnas está sim, mas como o @filipe-damasceno disse ainda não está apontando para um repositório público (está sendo providenciado)

**Comment by ramiresnas** [comment]
obrigado pela resposta @gabriellucius  e @filipe-damasceno, eu acabei optando em fazer as chamadas ao web service também, pelo memso motivo do @filipe-damasceno.
