### ISSUE TITLE
Repositório Nexus Maven Fora do ar

### ISSUE THREAD

**Issue by eduardomallmann** [pagseguro/pagseguro-java-sdk#38]
Prezados,

Ao realizar o comando gradle build, o mesmo não consegue recuperar as dependências do maven.
Verifiquei que o endereço:"http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/" está fora do ar.

Segue resposta ao realizar o gradle build:
`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve javax.servlet:javax.servlet-api:3.1.0.
  Required by:
      project :
   > Could not resolve javax.servlet:javax.servlet-api:3.1.0.
      > Could not get resource 'http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom'.
         > Could not HEAD 'http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom'.
            > repo.mvn.intranet.s2it.com.br: Name or service not known
> Could not resolve org.slf4j:slf4j-api:1.7.21.
  Required by:
      project :
   > Could not resolve org.slf4j:slf4j-api:1.7.21.
      > Could not get resource 'http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.pom'.
         > Could not HEAD 'http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.pom'.
            > repo.mvn.intranet.s2it.com.br
> Could not resolve commons-logging:commons-logging:1.2.
  Required by:
      project :
   > Could not resolve commons-logging:commons-logging:1.2.
      > Could not get resource 'http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/commons-logging/commons-logging/1.2/commons-logging-1.2.pom'.
         > Could not HEAD 'http://repo.mvn.intranet.s2it.com.br/nexus/content/groups/public/commons-logging/commons-logging/1.2/commons-logging-1.2.pom'.
            > repo.mvn.intranet.s2it.com.br
`
Há previsão para a resolução disto?

**Comment by iranmarcius** [comment]
Esse problema já é bem velho e impressionantemente os caras ainda não arrumaram no branch que você baixou, provavelmente. A solução paliativa que eu adotei aqui foi trocar o endereço do repositório para um endereço público. Funcionou pra mim.

**Comment by eduardomallmann** [comment]
Muito obrigado @iranmarcius!!! Resolvido!

Utilizei o repositório informado por Jone Schotten no [fórum da comunidade](https://comunidade.pagseguro.uol.com.br/hc/pt-br/community/posts/115000281674-Erro-ao-execute-o-comando-gradle-build-Java-): 
https://repository-master.mulesoft.org/nexus/content/groups/public/

Realmente, esperar por eles é complicado.

**Comment by gabriellucius** [comment]
@eduardomallmann  e @iranmarcius  esse problema foi corrigido,o projeto agora está disponível no Maven Global.
