### ISSUE TITLE
Versão de documentação completamente incompatível com esta versão 4.3.2 !

### ISSUE THREAD

**Issue by sergiomendonca** [pagseguro/pagseguro-java-sdk#58]
Primeiramente, não tem nenhum link para qualquer documentação JAVA do pagseguro no README, o que não faz sentido. Segundo, achei uma documentação de uma versão 2.2.0 que nem existe mais no maven (https://pagseguro.uol.com.br/v2/guia-de-integracao/documentacao-da-biblioteca-pagseguro-em-java.html#Address).

Onde está a documentação correta? Porque não deixam isso mais claro no REAME? Obrigado!!

**Comment by sergiomendonca** [comment]
Acho que é esse: https://devs.pagseguro.uol.com.br/docs/bibliotecas-java?_ga=2.187057646.7724762.1546421846-961330451.1545239624

**Comment by geekcom** [comment]
Exatamente esse link que @sergiomendonca citou
