### ISSUE TITLE
Faltando Paraná e Pernambuco está errado no enum de estados (State.java)

### ISSUE THREAD

**Issue by brunoliveiralcantara** [pagseguro/pagseguro-java-sdk#66]
O enum State não tem Paraná e Pernambuco está usando Paraná (PR).

https://github.com/pagseguro/pagseguro-java-sdk/blob/master/source/src/main/java/br/com/uol/pagseguro/api/common/domain/enums/State.java

**Comment by raphaelrejes** [comment]
Corrigido, obrigado!
